version: '3.8'

services:
  invoice-ocr:
    build:
      args:
        - PYTHON_VERSION=3.10
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./scripts:/app/scripts
      - ./data/models:/app/data/models
      - ./data/temp:/app/data/temp
      - ./data/output:/app/data/output
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    # Enable for debugging
    # command: ["sleep", "infinity"]
    # entrypoint: ["/bin/bash"]
    # stdin_open: true
    # tty: true

  redis:
    ports:
      - "6379:6379"

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
