version: '3.8'

services:
  invoice-ocr-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-ocr-dev
    ports:
      - "8000:8000"
      - "8888:8888"  # Jupyter
    volumes:
      - .:/app
      - ./data/models:/app/data/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]